name: Compilar PSP EBOOT
on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    container: pspdev/pspdev:latest
    steps:
      - uses: actions/checkout@v4

      - name: Compilar C++
        run: make

      - name: Subir EBOOT.PBP
        uses: actions/upload-artifact@v4
        with:
          name: ArbitroPSP_EBOOT
          path: EBOOT.PBP
