name: Compilar Juego PSP
on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    container: pspdev/pspdev:latest
    steps:
      - uses: actions/checkout@v4

      - name: Compilar C++
        run: make

      - name: Preparar Carpeta del Juego
        run: |
          mkdir -p ArbitroPSP
          cp EBOOT.PBP ArbitroPSP/
          cp -r assets ArbitroPSP/

      - name: Subir Juego Completo
        uses: actions/upload-artifact@v4
        with:
          name: ArbitroPSP_Juego_Completo
          path: ArbitroPSP/
